filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/golang/out.log  # Path to the log file inside the container

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "elastic123"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "https://kibana:5601"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
